package com.leoz.bz.zbase;

public enum ZBaseMessage {
	BM_SCAN_START,
	BM_SCAN_STOP,
	BM_SET_DIR,
	BM_SET_SIZE,
	BM_SET_THREADS,
	BM_DIR_LOAD_BEGIN,
	BM_DIR_LOAD_END,
	BM_FILE_LOAD_BEGIN,
	BM_FILE_LOAD_END,
	BM_FILE_COUNT,
	BM_CLEAR_CACHE_BEGIN,
	BM_CLEAR_CACHE_END
}
